export const jobs = [
  {
    id: 1,
    title: 'Cộng tác viên truyền thông y tế dự phòng',
    company: 'Sở Y tế Đà Nẵng',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận 1',
    type: 'Thời vụ',
    salary: '5.000.000 - 7.000.000',
    deadline: '15/05/2025',
    postedDate: '01/04/2025',
    experience: 'Không yêu cầu',
    position: 'Tuyên truyền y tế',
    level: 'Cộng tác viên',
    education: 'Trung cấp trở lên',
    gender: 'Tất cả',
    companyAddress: '12 Pasteur, Quận 1, TP.HCM',
    companyPhone: '028-12345678',
    companyEmail: 'hr@dananghealth.vn',
    companyWebsite: 'https://dananghealth.vn',
    projectCode: 'CTYTD-001',
    projectName: 'Truyền thông y tế dự phòng cộng đồng',
    projectType: 'Chương trình sức khỏe cộng đồng',
    projectTime: '01/03/2025 - 31/12/2025',
    projectSent: 'Đã triển khai tại 5 quận',
    vacancies: 7,
    description: `Tham gia truyền thông các chiến dịch phòng chống dịch bệnh tại cộng đồng.\n- Lên kế hoạch, tổ chức các buổi truyền thông, hội thảo.\n- Hỗ trợ xây dựng nội dung truyền thông sáng tạo, hấp dẫn.\n- Phối hợp với các đơn vị y tế địa phương để triển khai chương trình.`,
    requirements: [
      'Kỹ năng giao tiếp, thuyết trình tốt.',
      'Yêu thích hoạt động cộng đồng, năng động, sáng tạo.',
      'Ưu tiên ứng viên có kinh nghiệm truyền thông hoặc tổ chức sự kiện.'
    ],
    benefits: [
      'Lương thưởng hấp dẫn, hỗ trợ chi phí đi lại.',
      'Được đào tạo kỹ năng truyền thông chuyên sâu.',
      'Cơ hội mở rộng mối quan hệ trong ngành y tế.'
    ],
    status: 'Đang tuyển',
  },
  {
    id: 2,
    title: 'Kỹ thuật viên xét nghiệm y học',
    company: 'Bệnh viện Bạch Mai',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận 3',
    type: 'Toàn thời gian',
    salary: '12.000.000 - 15.000.000',
    deadline: '30/04/2025',
    postedDate: '10/04/2025',
    experience: '1-2 năm',
    position: 'Kỹ thuật viên',
    level: 'Nhân viên',
    education: 'Cao đẳng/Xét nghiệm',
    gender: 'Nam/Nữ',
    companyAddress: '78 Giải Phóng, Quận Đống Đa, Hà Nội',
    companyPhone: '024-38693731',
    companyEmail: 'tuyendung@bachmai.vn',
    companyWebsite: 'https://bachmai.gov.vn',
    projectCode: 'XN-2025',
    projectName: 'Nâng cao chất lượng xét nghiệm',
    projectType: 'Dự án y tế chuyên sâu',
    projectTime: '01/2025 - 12/2025',
    projectSent: 'Được tài trợ bởi Bộ Y tế',
    vacancies: 5,
    description: `Thực hiện các xét nghiệm y học hiện đại tại phòng lab đạt chuẩn quốc tế.\n- Vận hành, bảo trì các thiết bị xét nghiệm tự động.\n- Đảm bảo quy trình kiểm soát chất lượng nghiêm ngặt.\n- Tham gia đào tạo, cập nhật kiến thức chuyên môn định kỳ.`,
    requirements: [
      'Tốt nghiệp chuyên ngành kỹ thuật xét nghiệm y học.',
      'Có chứng chỉ hành nghề xét nghiệm.',
      'Cẩn thận, trung thực, có tinh thần trách nhiệm cao.'
    ],
    benefits: [
      'Lương ổn định, thưởng theo hiệu suất.',
      'Bảo hiểm sức khỏe, BHXH đầy đủ.',
      'Môi trường làm việc chuyên nghiệp, hiện đại.'
    ],
    status: 'Sắp hết hạn',
  },
  {
    id: 3,
    title: 'Bác sĩ đa khoa cộng đồng',
    company: 'Trung tâm Y tế Quận 7',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận 7',
    type: 'Bán thời gian',
    salary: '20.000.000 - 30.000.000',
    deadline: '10/06/2025',
    postedDate: '15/04/2025',
    experience: 'Trên 5 năm',
    position: 'Bác sĩ',
    level: 'Bác sĩ',
    education: 'Đại học Y',
    gender: 'Nam/Nữ',
    companyAddress: '25 Nguyễn Thị Thập, Quận 7, TP.HCM',
    companyPhone: '028-37750000',
    companyEmail: 'hr@ttytq7.vn',
    companyWebsite: 'https://ttytq7.vn',
    projectCode: 'BSCD-2025',
    projectName: 'Chăm sóc sức khỏe cộng đồng',
    projectType: 'Chương trình cộng đồng',
    projectTime: '03/2025 - 12/2025',
    projectSent: 'Đã khám cho 2000+ lượt bệnh nhân',
    vacancies: 10,
    description: `Khám, tư vấn và điều trị các bệnh lý phổ biến tại cộng đồng.\n- Tham gia các chương trình y tế dự phòng, tiêm chủng mở rộng.\n- Hỗ trợ đào tạo, hướng dẫn cộng tác viên y tế tuyến dưới.\n- Tham gia nghiên cứu, báo cáo chuyên môn định kỳ.`,
    requirements: [
      'Bằng bác sĩ đa khoa, ưu tiên có chứng chỉ hành nghề.',
      'Kinh nghiệm làm việc tại các trung tâm y tế cộng đồng.',
      'Kỹ năng giao tiếp, tư vấn sức khỏe tốt.'
    ],
    benefits: [
      'Lương cao, thưởng theo dự án.',
      'Được tham gia các hội thảo, đào tạo chuyên sâu.',
      'Cơ hội phát triển nghề nghiệp lâu dài.'
    ],
    status: 'Tin hết hạn',
  },
  {
    id: 4,
    title: 'Điều dưỡng viên chăm sóc nội trú',
    company: 'Bệnh viện Quốc tế Việt Pháp',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận Bình Thạnh',
    type: 'Toàn thời gian',
    salary: '14.000.000 - 18.000.000',
    deadline: '05/05/2025',
    postedDate: '20/04/2025',
    experience: '2-3 năm',
    position: 'Điều dưỡng',
    level: 'Nhân viên',
    education: 'Cao đẳng/Điều dưỡng',
    gender: 'Nữ',
    companyAddress: '6 Nguyễn Lương Bằng, Quận Bình Thạnh, TP.HCM',
    companyPhone: '028-39101111',
    companyEmail: 'tuyendung@vfphospital.vn',
    companyWebsite: 'https://vfphospital.vn',
    projectCode: 'DDVNT-2025',
    projectName: 'Chăm sóc nội trú chất lượng cao',
    projectType: 'Dịch vụ điều dưỡng',
    projectTime: '04/2025 - 12/2025',
    projectSent: 'Được đánh giá 5* bởi khách hàng',
    vacancies: 8,
    description: `Chăm sóc, theo dõi sức khỏe bệnh nhân nội trú tại bệnh viện quốc tế.\n- Hỗ trợ bác sĩ trong các thủ thuật, can thiệp y khoa.\n- Quản lý hồ sơ, cập nhật thông tin bệnh án điện tử.\n- Tham gia đào tạo, chia sẻ kinh nghiệm với đồng nghiệp.`,
    requirements: [
      'Tốt nghiệp điều dưỡng, có chứng chỉ hành nghề.',
      'Kinh nghiệm làm việc tại bệnh viện quốc tế là lợi thế.',
      'Tận tâm, chu đáo, chịu được áp lực công việc.'
    ],
    benefits: [
      'Lương cạnh tranh, thưởng lễ tết.',
      'Bảo hiểm sức khỏe cao cấp.',
      'Được đào tạo nâng cao chuyên môn, kỹ năng mềm.'
    ],
    status: 'Đang tuyển',
  },
  {
    id: 5,
    title: 'Nhân viên tư vấn sức khỏe online',
    company: 'Phòng khám Đa khoa 24h',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận 10',
    type: 'Làm việc từ xa',
    salary: '8.000.000 - 10.000.000',
    deadline: '25/05/2025',
    postedDate: '22/04/2025',
    experience: '1-2 năm',
    position: 'Tư vấn sức khỏe',
    level: 'Nhân viên',
    education: 'Đại học',
    gender: 'Tất cả',
    companyAddress: '24 Lê Hồng Phong, Quận 10, TP.HCM',
    companyPhone: '028-38345678',
    companyEmail: 'contact@pkdk24h.vn',
    companyWebsite: 'https://pkdk24h.vn',
    projectCode: 'TVSK-2025',
    projectName: 'Tư vấn sức khỏe trực tuyến',
    projectType: 'Dịch vụ tư vấn',
    projectTime: '02/2025 - 12/2025',
    projectSent: 'Đã tư vấn cho 10.000+ khách hàng',
    vacancies: 15,
    description: `Tư vấn sức khỏe cho khách hàng qua điện thoại, chat, video call.\n- Hỗ trợ giải đáp thắc mắc về dinh dưỡng, phòng bệnh.\n- Đề xuất giải pháp chăm sóc sức khỏe cá nhân hóa.\n- Tham gia xây dựng nội dung tư vấn online hấp dẫn.`,
    requirements: [
      'Có kinh nghiệm tư vấn sức khỏe, giao tiếp tốt.',
      'Thành thạo tin học văn phòng, sử dụng tốt các nền tảng online.',
      'Chủ động, linh hoạt, yêu thích công việc hỗ trợ khách hàng.'
    ],
    benefits: [
      'Làm việc linh hoạt, không cần đến văn phòng.',
      'Thưởng theo hiệu suất tư vấn.',
      'Được đào tạo kỹ năng tư vấn chuyên sâu.'
    ],
    status: 'Đang tuyển',
  },
  {
    id: 6,
    title: 'Cộng tác viên tầm soát ung thư cổ tử cung',
    company: 'Trung tâm Y tế Dự phòng',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận 5',
    type: 'Bán thời gian',
    salary: 'Thỏa thuận',
    deadline: '18/05/2025',
    postedDate: '25/04/2025',
    experience: 'Không yêu cầu',
    position: 'Tầm soát ung thư',
    level: 'Cộng tác viên',
    education: 'Trung cấp trở lên',
    gender: 'Nữ',
    companyAddress: '5 Nguyễn Trãi, Quận 5, TP.HCM',
    companyPhone: '028-39234567',
    companyEmail: 'ctv@yteduphong.vn',
    companyWebsite: 'https://yteduphong.vn',
    projectCode: 'TSUTCTC-2025',
    projectName: 'Tầm soát ung thư cổ tử cung',
    projectType: 'Chương trình dự phòng',
    projectTime: '05/2025 - 12/2025',
    projectSent: 'Đã tầm soát cho 5000+ phụ nữ',
    vacancies: 12,
    description: `Hỗ trợ triển khai chương trình tầm soát ung thư cổ tử cung tại các phường trung tâm.\n- Tư vấn, hướng dẫn người dân tham gia xét nghiệm.\n- Ghi nhận, tổng hợp dữ liệu, báo cáo kết quả chương trình.\n- Tham gia các buổi tập huấn, đào tạo chuyên môn.`,
    requirements: [
      'Yêu thích công tác cộng đồng, giao tiếp tốt.',
      'Có khả năng di chuyển, làm việc ngoài trời.',
      'Ưu tiên ứng viên từng tham gia các chương trình y tế dự phòng.'
    ],
    benefits: [
      'Thù lao theo buổi, hỗ trợ chi phí đi lại.',
      'Được đào tạo miễn phí về chuyên môn.',
      'Cơ hội trở thành nhân viên chính thức nếu làm tốt.'
    ],
    status: 'Đang tuyển',
  },
  {
    id: 7,
    title: 'Nhân viên hỗ trợ y tế dự phòng',
    company: 'Trung tâm Kiểm soát Bệnh tật',
    locationProvince: 'Thành phố Hồ Chí Minh',
    locationWard: 'Quận Phú Nhuận',
    type: 'Toàn thời gian',
    salary: '9.000.000 - 13.000.000',
    deadline: '28/05/2025',
    postedDate: '28/04/2025',
    experience: '2-3 năm',
    position: 'Hỗ trợ dự phòng',
    level: 'Nhân viên',
    education: 'Trung cấp trở lên',
    gender: 'Nam',
    companyAddress: '120 Phan Đăng Lưu, Phú Nhuận, TP.HCM',
    companyPhone: '028-39999999',
    companyEmail: 'hr@ksbtd.vn',
    companyWebsite: 'https://ksbtd.vn',
    projectCode: 'HTYTD-2025',
    projectName: 'Hỗ trợ y tế dự phòng cộng đồng',
    projectType: 'Chương trình dự phòng',
    projectTime: '04/2025 - 12/2025',
    projectSent: 'Đã hỗ trợ 100+ điểm tiêm chủng',
    vacancies: 20,
    description: `Hỗ trợ các điểm tiêm chủng, phòng chống dịch bệnh tại cộng đồng.\n- Tham gia tổ chức, giám sát các chiến dịch tiêm chủng.\n- Hỗ trợ nhập liệu, quản lý hồ sơ sức khỏe cộng đồng.\n- Tham gia các hoạt động truyền thông, giáo dục sức khỏe.`,
    requirements: [
      'Kinh nghiệm hỗ trợ y tế, chịu được áp lực.',
      'Kỹ năng làm việc nhóm, phối hợp tốt với đồng nghiệp.',
      'Ưu tiên ứng viên có bằng cấp liên quan.'
    ],
    benefits: [
      'Lương ổn định, thưởng theo kết quả công việc.',
      'Bảo hiểm đầy đủ, chế độ phúc lợi tốt.',
      'Được tham gia các khóa đào tạo nâng cao.'
    ],
    status: 'Đang tuyển',
  }
]; 